name: Deploy Site

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Build validation
        run: |
          html5validator --root . --ignore "*.md"
          css-validator css/main.css
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "."
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
